title: Tanner's Blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "Tanner"
  email: "NULL"
  url: "https://txnn3r.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Tanner"
year : "2023"
